// config.js
const configTable = {
    "1": {
		name: "liars bar",
		title: "Dive into this multiplayer online experience set in a sketchy bar where the games are as dangerous as the patrons.",
        logo: "images/1/logo.jpg",
		videopic: "images/1/videopic.jpg",
		videourl: "https://video.cloudflare.steamstatic.com/store_trailers/257054157/movie480_vp9.webm?t=1726652021",
		star: ' 4.8',
		downsize: "300MB",
		disksize: "400MB",
		type: "online pvp",
		pic1: "images/1/pic1.jpg",
		pic2: "images/1/pic2.jpg",
		pic3: "images/1/pic3.jpg",
        description: "Welcome to Liar's Bar: The Ultimate Deception Playground!\nStep into Liar's Bar, the most twisted and thrilling hangout in town. This isn't your average pub – it's a den of lies, deception, and mind games. Grab a seat at a table of four and immerse yourself in the ultimate first-person multiplayer online experience where cunning and trickery are the name of the game.\nPlayers take turns playing a card face down and declaring its value. The value should match the table’s value. (e.g., 'King' or 'Queen').\nWhen a player lays down a card, they might be lying about its value. If you suspect a lie, you can call their bluff.\nIf someone’s bluff is called and they were lying, they must play a round of Russian Roulette. Surviving one bullet out of 6 rounds of shells means you stay in the game;\n failing means game over for you.\nAfter Russian Roulette is played, the cards are reset, and the game continues.",
		androidbtn: "Android Download Now!",
		androidurl: "http://www.baidu.com",
		iosbtn: "Available for iOS download on January 5, 2025",
		iosurl: "http://www.google.com",
    },
    "2": {
		name: "Lethal Company",
		title: "A co-op horror about scavenging at abandoned moons to sell scrap to the Company.",
        logo: "images/2/logo.jpg",
		videopic: "images/2/videopic.jpg",
		videourl: "https://video.cloudflare.steamstatic.com/store_trailers/256961309/movie480_vp9.webm?t=1690909590",
		star: ' 4.9',
		downsize: "500MB",
		disksize: "550MB",
		type: "online PvP",
		pic1: "images/2/pic1.jpg",
		pic2: "images/2/pic2.jpg",
		pic3: "images/2/pic3.jpg",
        description: "You are a contracted worker for the Company. Your job is to collect scrap from abandoned, industrialized moons to meet the Company's profit quota. You can use the cash you earn to travel to new moons with higher risks and rewards--or you can buy fancy suits and decorations for your ship. Experience nature, scanning any creature you find to add them to your bestiary. Explore the wondrous outdoors and rummage through their derelict, steel and concrete underbellies. Just never miss the quota.\nThese dangers prey upon the vulnerable and lonesome, and the protection of your crew may be your only hope. You can guide your crewmates from your ship, using the radar to call out traps and using the ship's terminal to access remotely locked doors--or you can all go in together. The Company store has many useful tools for the job, including lights, shovels, walkie talkies, stun grenades, or boomboxes.\nThings get dangerous at night. Communicate with your crewmates to carry all valuables to the ship before things get too dangerous, and try not to leave anyone behind.\n",
		androidbtn: "Available for iOS download on January 10, 2025",
		androidurl: "#",
		iosbtn: "Available for iOS download on January 10, 2025",
		iosurl: "#",
    },
    "3": {
		name: "Thronefall",
		title: "A minimalist game about building and defending your little kingdom.",
        logo: "images/3/logo.jpg",
		videopic: "images/3/videopic.jpg",
		videourl: "https://video.cloudflare.steamstatic.com/store_trailers/257063854/movie480_vp9.webm?t=1728664219",
		star: ' 4.7',
		downsize: "350MB",
		disksize: "400MB",
		type: "Single-player",
		pic1: "images/3/pic1.jpg",
		pic2: "images/3/pic2.jpg",
		pic3: "images/3/pic3.jpg",
        description: "Saddle the horses! See your kingdom come to life, fight gripping battles to defend it and still be done in time for lunch.\nWith Thronefall we tried to strip a classic strategy game from all unnecessary complexity, combining it with some healthy hack and slay. Build up your base during the day, defend it til your last breath at night.\nWill you be able to strike the right balance between economy and defence? Do you need more archers, thicker walls or an additional mill? Will you keep the enemies at bay with your longbow or charge your horse right into them? It's going to be a tough night, but nothing beats seeing the sun rise above your little kingdom to live another day.",
		androidbtn: "Available for iOS download on January 15, 2025",
		androidurl: "#",
		iosbtn: "Available for iOS download on January 15, 2025",
		iosurl: "#",
    },
	"4": {
		name: "TCG Card Shop Simulator",
		title: "Open your own local game store. Stock shelves with the latest booster packs, or crack them and collect the cards for yourself. ",
        logo: "images/4/logo.jpg",
		videopic: "images/4/videopic.jpg",
		videourl: "https://video.cloudflare.steamstatic.com/store_trailers/257039617/movie480_vp9.webm?t=1721658593",
		star: ' 5.0',
		downsize: "230MB",
		disksize: "280MB",
		type: "online PvP",
		pic1: "images/4/pic1.jpg",
		pic2: "images/4/pic2.jpg",
		pic3: "images/4/pic3.jpg",
        description: "TCG Card Shop Simulator is a trading card shop simulation where you sell card booster packs to earn money and build your card shop business.\nManage Your Shop:\nDesign your own TCG shop. Organize shelves and card packs to make customer shopping experience smooth and easy.\nCard Collection:\nOpen the booster packs yourself and collect the cards. Find rare cards and sell them to make a fortune, or keep them to complete your card collection.\nHost Game:\nSet your card game format and fee, invite players to play card games in your shop. Be sure to keep your store clean and hygienic for the players or they might leave!\nOrder Products:\nStock up on different booster card packs and card game products. Keep track of popular trends and adjust your inventory to cater to the ever-changing demands of your customers.\nExpand Your Business:Earn profits to reinvest in your shop. Expand your space, unlock new card sets, and upgrade your facilities to attract even more customers and increase revenue.\n",
		androidbtn: "Available for iOS download on January 3, 2025",
		androidurl: "#",
		iosbtn: "Available for iOS download on January 3, 2025",
		iosurl: "#",
    },
	"5": {
		name: "Tactical Breach Wizards",
		title: "In Tactical Breach Wizards, you lead a team of renegade wizards in kevlar through turn-based battles to unravel a modern conspiracy plot. ",
        logo: "images/5/logo.jpg",
		videopic: "images/5/videopic.jpg",
		videourl: "https://video.cloudflare.steamstatic.com/store_trailers/257029830/movie480_vp9.webm?t=1724174127",
		star: ' 4.9',
		downsize: "450MB",
		disksize: "550MB",
		type: "Single-player",
		pic1: "images/5/pic1.jpg",
		pic2: "images/5/pic2.jpg",
		pic3: "images/5/pic3.jpg",
        description: "Tactical Breach Wizards is a turn-based tactics game in which you lead a team of renegade wizards in kevlar, as they unravel a modern conspiracy plot and/or find the most stylish way to punch a Traffic Warlock through a 4th story window.\nIt's a story-driven campaign of about 14 hours, in which you...\nEach of your wizards has a unique set of abilities, from a straightforward lightning bolt to transforming into a rabid dog.\nWhen you hit a tricky situation, try every wild idea you have - you can always rewind if it didn't pan out. It could work beautifully, fail spectacularly, or screw up in a way that gives you new ideas. Either way, free rewinds mean you play it out in-game instead of scratching your head.\n",
		androidbtn: "Available for iOS download on January 10, 2025",
		androidurl: "#",
		iosbtn: "Available for iOS download on January 10, 2025",
		iosurl: "#",
    },
};

// 导出配置表
//export default configTable;
